# Solve problem 1

In [21]:
import numpy as np

In [22]:
def array(n):
    return np.arange(0, n)[::-1]
array(10)

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

# Solve problem 2

In [87]:
def matrica():
    return np.diag(np.arange(1,5), k=0)
print(matrica())
print('Сумма значений по диагонали равна', np.diag(np.arange(1,5), k=0).sum())

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]
Сумма значений по диагонали равна 10


# Solve problem 3

In [105]:
#4x + 2y + z = 4
#x + 3y = 12
#5y + 4z = -3

a = np.array([[4, 2, 1], [1, 3, 0], [0, 5, 4]])
b = np.array([4, 12, -3])

from numpy import linalg

linalg.solve(a, b)

array([ 0.46666667,  3.84444444, -5.55555556])

# Solve problem 4

In [117]:
users_stats = np.array(
    [
        [2, 1, 0, 0, 0, 0],
        [1, 1, 2, 1, 0, 0],
        [2, 0, 1, 0, 0, 0],
        [1, 1, 2, 1, 0, 1],
        [0, 0, 1, 2, 0, 0],
        [0, 0, 0, 0, 0, 5],
        [1, 0, 0, 0, 0, 0],
        [0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 3],
        [1, 0, 0, 2, 1, 4]
    ], 
    np.int32
)

next_user_stats = np.array([0, 1, 2, 0, 0, 0])

In [201]:
a = users_stats
b = next_user_stats

def cosine(a, b):
    a_length = linalg.norm(a[7])
    b_length = linalg.norm(b)
    
    """У юзера с массивом а[7] = [0, 1, 1, 0, 0, 0] самое близкое 
    расположение вектора к вектору нашего нового покупателя"""
    
    return np.dot(a[7], b) / (a_length*b_length)

print('Косинусное сходство от 0 до 1:', cosine(a, b))
print('Угол между векторами:', np.arccos(cosine(a, b)) * 360 / 2 / np.pi)

Косинусное сходство от 0 до 1: 0.9486832980505138
Угол между векторами: 18.434948822922017
